package com.prezi.haxe.gradle;

import com.google.common.base.Charsets;
import com.google.common.base.Joiner;
import com.google.common.base.Predicate;
import com.google.common.collect.Iterables;
import com.google.common.io.Files;
import org.apache.commons.io.FileUtils;
import org.gradle.api.DomainObjectSet;
import org.gradle.language.base.LanguageSourceSet;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;

public class HaxeTestCompile extends HaxeCompile {
	private static final Pattern EXAMPLE_TEST_LINE = Pattern.compile("(import |\\s*add\\()ExampleTest\\)?;");
	private File workingDirectory;

	@Override
	public void compile() throws IOException, InterruptedException {
		File workDir = getWorkingDirectory();
		FileUtils.deleteDirectory(workDir);
		FileUtils.forceMkdir(workDir);

		File testsDir = getTestsDirectory();

		for (File sourceDir : super.getSourceDirectories(getSourceSets())) {
			if (sourceDir.exists()) {
				FileUtils.copyDirectory(sourceDir, testsDir);
			}
		}


		List<String> cmd = Arrays.asList("haxelib", "run", "munit", "gen", testsDir.getName());
		CommandExecutor.execute(cmd, workDir, new DefaultExecutionResultHandler(cmd));

		// Delete ExampleTest.hx generated by MUnit
		FileUtils.forceDelete(new File(testsDir, "ExampleTest.hx"));
		File suite = new File(testsDir, "TestSuite.hx");
		if (suite.exists()) {
			List<String> suiteText = Files.readLines(suite, Charsets.UTF_8);
			FileUtils.forceDelete(suite);
			Files.write(Joiner.on("\n").join(Iterables.filter(suiteText, new Predicate<String>() {
				@Override
				public boolean apply(String line) {
					return !EXAMPLE_TEST_LINE.matcher(line).matches();
				}

			})), suite, Charsets.UTF_8);
		}


		super.compile();
	}

	@Override
	protected HaxeCommandBuilder configureHaxeCommandBuilder(File output, DomainObjectSet<LanguageSourceSet> sources) {
		HaxeCommandBuilder builder = super.configureHaxeCommandBuilder(output, sources);
		if (getProject().hasProperty("munit.debug")) {
			builder.withFlags(new ArrayList<String>(Arrays.asList("-D testDebug")));
		}

		return builder;
	}

	@Override
	protected String getMainClass() {
		return "TestMain";
	}

	@Override
	protected Set<File> getSourceDirectories(DomainObjectSet<LanguageSourceSet> sources) {
		return Collections.singleton(getTestsDirectory());
	}

	public File getTestsDirectory() {
		return new File(getWorkingDirectory(), "tests");
	}

	public void workingDirectory(Object workingDirectory) {
		setWorkingDirectory(workingDirectory);
	}
	public File getWorkingDirectory() {
		return workingDirectory;
	}
	public void setWorkingDirectory(Object workingDirectory) {
		this.workingDirectory = getProject().file(workingDirectory);
	}
}
